"""add subdivision table and link to karyawan

Revision ID: e62beeaf3f1a
Revises: ac8c65e9eaa7
Create Date: 2026-07-12 20:51:50.443903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e62beeaf3f1a'
down_revision: Union[str, Sequence[str], None] = 'ac8c65e9eaa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subdivisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('division_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('karyawan_details', sa.Column('subdivision_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('fk_karyawan_division'), 'karyawan_details', type_='foreignkey')
    op.create_foreign_key(None, 'karyawan_details', 'subdivisions', ['subdivision_id'], ['id'])
    op.drop_column('karyawan_details', 'division_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('karyawan_details', sa.Column('division_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'karyawan_details', type_='foreignkey')
    op.create_foreign_key(op.f('fk_karyawan_division'), 'karyawan_details', 'divisions', ['division_id'], ['id'])
    op.drop_column('karyawan_details', 'subdivision_id')
    op.drop_table('subdivisions')
    # ### end Alembic commands ###
