"""add work_duration_minutes

Revision ID: f38673e607ea
Revises: 95699de21c1b
Create Date: 2026-04-22 22:18:58.878269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f38673e607ea'
down_revision: Union[str, Sequence[str], None] = '95699de21c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('work_duration_minutes', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'divisions', ['name'])
    op.alter_column('karyawan_details', 'alamat_lengkap',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('karyawan_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('karyawan_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_karyawan_details_id'), table_name='karyawan_details')
    op.drop_constraint(op.f('karyawan_details_user_id_fkey'), 'karyawan_details', type_='foreignkey')
    op.create_foreign_key(None, 'karyawan_details', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'karyawan_details', type_='foreignkey')
    op.create_foreign_key(op.f('karyawan_details_user_id_fkey'), 'karyawan_details', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_karyawan_details_id'), 'karyawan_details', ['id'], unique=False)
    op.alter_column('karyawan_details', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('karyawan_details', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('karyawan_details', 'alamat_lengkap',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'divisions', type_='unique')
    op.drop_column('attendances', 'work_duration_minutes')
    # ### end Alembic commands ###
